Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/a/apuglia/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "espresso"
executable              = runner.sh
arguments               = 
output                  = condor/output/fns.out
error                   = condor/error/fns.err
log                     = condor/log/fns.log
queue
