Proxy_filename          = x509up
Proxy_path              = /afs/cern.ch/user/a/apuglia/private/$(Proxy_filename)
universe                = vanilla
x509userproxy           = $(Proxy_path)
use_x509userproxy       = true
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = $(Proxy_path)
+JobFlavour             = "espresso"
executable              = runner.sh
arguments               = 
output                  = /eos/user/a/apuglia/SWAN_projects/thesis/CMSSW_14_1_7/src/PhysicsTools/NanoAODTools/python/postprocessing/condor_provacondor/output/fns.out
error                   = /eos/user/a/apuglia/SWAN_projects/thesis/CMSSW_14_1_7/src/PhysicsTools/NanoAODTools/python/postprocessing/condor_provacondor/error/fns.err
log                     = /eos/user/a/apuglia/SWAN_projects/thesis/CMSSW_14_1_7/src/PhysicsTools/NanoAODTools/python/postprocessing/condor_provacondor/log/fns.log
queue
